# Generated by Django 3.0.2 on 2020-04-20 22:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donatepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField(max_length=1500, null=True)),
                ('link', models.CharField(max_length=150, null=True)),
                ('need', models.PositiveIntegerField(blank=True, null=True)),
                ('daonated', models.PositiveIntegerField(default='0', null=True)),
            ],
        ),
    ]
