# Generated by Django 3.0.2 on 2020-04-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_donate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatepage',
            name='project',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
