# Generated by Django 3.0.2 on 2020-04-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_donate', '0002_donatepage_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatepage',
            name='daonated',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
