# Generated by Django 3.0.2 on 2020-04-18 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Showresume',
            new_name='Resume',
        ),
    ]
